[mypy]
python_version = 3.12
warn_return_any = False
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True
check_untyped_defs = False
disallow_incomplete_defs = False
no_implicit_optional = False
warn_no_return = False

# 특정 모듈 무시
[mypy-passlib.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-sqlalchemy.*]
ignore_missing_imports = True
