"""add_reports_table

Revision ID: 2021af522224
Revises: b7a218441ebe
Create Date: 2025-11-26 13:26:30.429381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2021af522224'
down_revision: Union[str, Sequence[str], None] = 'b7a218441ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False, comment='신고 ID'),
    sa.Column('reporter_id', sa.Integer(), nullable=False, comment='신고자 ID'),
    sa.Column('question_id', sa.Integer(), nullable=True, comment='신고된 질문 ID'),
    sa.Column('answer_id', sa.Integer(), nullable=True, comment='신고된 답변 ID'),
    sa.Column('reason', sa.String(length=50), nullable=False, comment='신고 사유 (SPAM, ABUSE, INAPPROPRIATE, OTHER)'),
    sa.Column('description', sa.Text(), nullable=True, comment='상세 설명'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='처리 상태 (PENDING, REVIEWED, RESOLVED, REJECTED)'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='관리자 메모'),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='처리 일시'),
    sa.Column('processed_by', sa.Integer(), nullable=True, comment='처리자 ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='신고 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'answer_id', name='uq_reporter_answer'),
    sa.UniqueConstraint('reporter_id', 'question_id', name='uq_reporter_question'),
    comment='질문/답변 신고'
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.alter_column('tino_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               comment='거래 타입 (INITIAL, QUESTION_BOUNTY, ANSWER_REWARD, REFUND, ADMIN_ADJUST, PURCHASE, BONUS)',
               existing_comment='거래 타입',
               existing_nullable=False)
    op.alter_column('users', 'tino_balance',
               existing_type=sa.INTEGER(),
               comment='TINO 토큰 잔액 (신규가입 보너스: 10)',
               existing_comment='TINO 토큰 잔액',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tino_balance',
               existing_type=sa.INTEGER(),
               comment='TINO 토큰 잔액',
               existing_comment='TINO 토큰 잔액 (신규가입 보너스: 10)',
               existing_nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('tino_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               comment='거래 타입',
               existing_comment='거래 타입 (INITIAL, QUESTION_BOUNTY, ANSWER_REWARD, REFUND, ADMIN_ADJUST, PURCHASE, BONUS)',
               existing_nullable=False)
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
