"""create_initial_tables

Revision ID: e343a5fe59ad
Revises: 
Create Date: 2025-11-21 07:22:32.214079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e343a5fe59ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_email_domains',
    sa.Column('id', sa.Integer(), nullable=False, comment='도메인 ID'),
    sa.Column('domain', sa.String(length=100), nullable=False, comment='이메일 도메인 (예: @tukorea.ac.kr)'),
    sa.Column('university_name', sa.String(length=100), nullable=True, comment='대학교 이름'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    comment='허용된 이메일 도메인'
    )
    op.create_index(op.f('ix_allowed_email_domains_id'), 'allowed_email_domains', ['id'], unique=False)
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False, comment='인증 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='6자리 인증 코드'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='만료 일시'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='인증 완료 여부'),
    sa.Column('attempt_count', sa.Integer(), nullable=False, comment='시도 횟수'),
    sa.Column('resend_count', sa.Integer(), nullable=False, comment='재전송 횟수'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='이메일 인증 코드'
    )
    op.create_index(op.f('ix_email_verifications_email'), 'email_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False, comment='관심사 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='관심사명'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='관심사 키워드'
    )
    op.create_index(op.f('ix_interests_id'), 'interests', ['id'], unique=False)
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False, comment='전공 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='전공명'),
    sa.Column('code', sa.String(length=20), nullable=True, comment='전공 코드'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 상태'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='전공 정보'
    )
    op.create_index(op.f('ix_majors_id'), 'majors', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='해시된 비밀번호'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='닉네임'),
    sa.Column('grade', sa.Integer(), nullable=True, comment='학년 (1-4)'),
    sa.Column('major_id', sa.Integer(), nullable=True, comment='전공 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 상태'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='이메일 인증 여부'),
    sa.Column('privacy_policy_agreed_at', sa.DateTime(timezone=True), nullable=True, comment='개인정보 처리방침 동의 일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='사용자 정보'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False, comment='이력 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 주소'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='User Agent'),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='로그인 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='로그인 이력'
    )
    op.create_index(op.f('ix_login_history_id'), 'login_history', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='토큰 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('token', sa.Text(), nullable=False, comment='리프레시 토큰'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='만료 일시'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='리프레시 토큰 저장'
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('user_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interest_id'),
    comment='사용자-관심사 매핑'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_login_history_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_majors_id'), table_name='majors')
    op.drop_table('majors')
    op.drop_index(op.f('ix_interests_id'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_email'), table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index(op.f('ix_allowed_email_domains_id'), table_name='allowed_email_domains')
    op.drop_table('allowed_email_domains')
    # ### end Alembic commands ###
